# These are supported funding model platforms

github: [MAF2414]
# ko_fi: # Replace with your Ko-fi username if you set one up
# buy_me_a_coffee: # Replace with your Buy Me a Coffee username
# custom: ['https://your-donation-link.com']
